// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360Pro.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote360Pro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614042050_ActMdeloVoos")]
    partial class ActMdeloVoos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlianzaPoliticaPartidoPolitico", b =>
                {
                    b.Property<int>("AlianzasId")
                        .HasColumnType("int");

                    b.Property<int>("PartidosId")
                        .HasColumnType("int");

                    b.HasKey("AlianzasId", "PartidosId");

                    b.HasIndex("PartidosId");

                    b.ToTable("AlianzaPoliticaPartidoPolitico");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AlianzaPolitica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("AlianzasPoliticas", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AsignacionCandidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("PuestoElectivoId");

                    b.ToTable("AsignacionesCandidatos");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AsignacionDirigente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoPoliticoId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionDirigente");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoPoliticoId");

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Ciudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciudadano");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CodigoVerificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("int");

                    b.Property<int?>("CiudadanoId1")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("CiudadanoId1");

                    b.HasIndex("EleccionId");

                    b.ToTable("CodigosVerificacion", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoEleccion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Elecciones", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.EleccionPuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<int?>("EleccionId1")
                        .HasColumnType("int");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.Property<int?>("PuestoElectivoId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("EleccionId1");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("PuestoElectivoId1");

                    b.ToTable("EleccionPuestoElectivo", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartidoPolitico");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PartidoPoliticoId")
                        .HasColumnType("int");

                    b.Property<int>("RolUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("int");

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVotacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("EleccionId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VotoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.Property<int>("VotoId")
                        .HasColumnType("int");

                    b.Property<int?>("VotoId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("VotoId");

                    b.HasIndex("VotoId1");

                    b.ToTable("VotoDetalles", (string)null);
                });

            modelBuilder.Entity("AlianzaPoliticaPartidoPolitico", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.AlianzaPolitica", null)
                        .WithMany()
                        .HasForeignKey("AlianzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PartidoPolitico", null)
                        .WithMany()
                        .HasForeignKey("PartidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AsignacionCandidato", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany("AsignacionesCandidatos")
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AsignacionDirigente", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PartidoPolitico", "PartidoPolitico")
                        .WithOne("AsignacionDirigente")
                        .HasForeignKey("eVote360Pro.Core.Domain.Entities.AsignacionDirigente", "PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidoPolitico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PartidoPolitico", "PartidoPolitico")
                        .WithMany("Candidatos")
                        .HasForeignKey("PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartidoPolitico");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CodigoVerificacion", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Ciudadano", null)
                        .WithMany("CodigosVerificacion")
                        .HasForeignKey("CiudadanoId1");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudadano");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.EleccionPuestoElectivo", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Eleccion", null)
                        .WithMany("PuestosElectivos")
                        .HasForeignKey("EleccionId1");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PuestoElectivo", null)
                        .WithMany("Elecciones")
                        .HasForeignKey("PuestoElectivoId1");

                    b.Navigation("Eleccion");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Voto", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidato", null)
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Ciudadano", null)
                        .WithMany("Votos")
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VotoDetalle", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Voto", "Voto")
                        .WithMany()
                        .HasForeignKey("VotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Voto", null)
                        .WithMany("VotoDetalles")
                        .HasForeignKey("VotoId1");

                    b.Navigation("Candidato");

                    b.Navigation("PuestoElectivo");

                    b.Navigation("Voto");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Ciudadano", b =>
                {
                    b.Navigation("CodigosVerificacion");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Eleccion", b =>
                {
                    b.Navigation("PuestosElectivos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Navigation("AsignacionDirigente")
                        .IsRequired();

                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Navigation("AsignacionesCandidatos");

                    b.Navigation("Elecciones");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Voto", b =>
                {
                    b.Navigation("VotoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
